function doPost(e) {
  try {
    // Parse the JSON payload sent from the Vercel webhook
    const data = JSON.parse(e.postData.contents);
    
    const { sessionId, totalAmount, currency, customerEmail, metadata, lineItems } = data;
    
    // Format currency (Stripe sends amount in cents/pence)
    const formattedTotal = (totalAmount / 100).toFixed(2);
    const currencySymbol = currency.toUpperCase() === 'GBP' ? '£' : currency.toUpperCase();

    // Format line items for the email body
    const itemsList = lineItems.map(item => {
      const itemAmount = (item.amount / 100).toFixed(2);
      return `<li>${item.name} (Qty: ${item.quantity}) - ${currencySymbol}${itemAmount}</li>`;
    }).join('');

    // Format metadata (client details)
    const clientDetails = `
      <p><strong>Client Name:</strong> ${metadata.name || 'N/A'}</p>
      <p><strong>Client Phone:</strong> ${metadata.phone || 'N/A'}</p>
      <p><strong>Company Name:</strong> ${metadata.company || 'N/A'}</p>
      <p><strong>Jurisdiction:</strong> ${metadata.jurisdiction || 'N/A'}</p>
      ${metadata.invoice ? `<p><strong>Invoice Number:</strong> ${metadata.invoice}</p>` : ''}
      <p><strong>Payment Type:</strong> ${metadata.payment_type || 'N/A'}</p>
    `;

    const subject = `[NEW ORDER] Payment Confirmed: ${currencySymbol}${formattedTotal} from ${metadata.name || customerEmail}`;
    
    const htmlBody = `
      <html>
        <body>
          <h2>✅ Stripe Payment Confirmation</h2>
          <p>A new payment has been successfully processed via Stripe Checkout.</p>
          
          <h3>Transaction Details</h3>
          <p><strong>Session ID:</strong> ${sessionId}</p>
          <p><strong>Customer Email:</strong> ${customerEmail}</p>
          <p><strong>Total Paid:</strong> ${currencySymbol}${formattedTotal} ${currency.toUpperCase()}</p>
          
          <h3>Client & Order Information</h3>
          ${clientDetails}

          <h3>Items Purchased</h3>
          <ul>
            ${itemsList}
          </ul>
          
          <p>Please log into the Stripe Dashboard to view the full transaction details.</p>
          <hr>
          <p style="font-size: 10px; color: #999;">This email was generated by the One Offshore Company Webhook Handler.</p>
        </body>
      </html>
    `;

    // Send the email to both admin addresses
    MailApp.sendEmail({
      to: "accounts@oneoffshorecompany.com",
      cc: "info@oneoffshorecompany.com",
      subject: subject,
      htmlBody: htmlBody
    });

    return ContentService.createTextOutput(JSON.stringify({ success: true })).setMimeType(ContentService.MimeType.JSON);

  } catch (error) {
    Logger.log("Error processing webhook: " + error.toString());
    return ContentService.createTextOutput(JSON.stringify({ success: false, error: error.toString() })).setMimeType(ContentService.MimeType.JSON);
  }
}